<html>
<head>
<title>
CppUnit - The Unit Testing Library
</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
<link href="tabs.css" rel="stylesheet" type="text/css">
</head>

<body bgcolor="#ffffff"> 
<table width="100%">
  <tr>
    <td width="40%" align="left" valign="center">
      <a href="http://sourceforge.net/projects/cppunit">
      CppUnit project page
      </a>
    </td>
    <td>
      <a href="FAQ">FAQ</a>
    </td>
    <td width="40%" align="right" valign="center">
      <a href="http://cppunit.sourceforge.net">CppUnit home page</a>
    </td>
  </tr>
</table>

<hr>
<!-- Generated by Doxygen 1.7.4 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.html"><span>Class&#160;List</span></a></li>
      <li><a href="classes.html"><span>Class&#160;Index</span></a></li>
      <li><a href="inherits.html"><span>Class&#160;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pro-attribs">Protected Attributes</a> &#124;
<a href="#pri-methods">Private Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">TestFailure Class Reference<div class="ingroups"><a class="el" href="group___browsing_collected_test_result.html">Browsing collected test result</a></div></div>  </div>
</div>
<div class="contents">
<!-- doxytag: class="TestFailure" -->
<p>Record of a failed <a class="el" href="class_test.html" title="Base class for all test objects.All test objects should be a subclass of Test. Some test objects...">Test</a> execution.A <a class="el" href="class_test_failure.html" title="Record of a failed Test execution.A TestFailure collects a failed test together with the caught excep...">TestFailure</a> collects a failed test together with the caught exception.  
 <a href="class_test_failure.html#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_test_failure_8h_source.html">TestFailure.h</a>&gt;</code></p>
<div class="dynheader">
Collaboration diagram for TestFailure:</div>
<div class="dyncontent">
<div class="center"><img src="class_test_failure__coll__graph.png" border="0" usemap="#_test_failure_coll__map" alt="Collaboration graph"/></div>
<map name="_test_failure_coll__map" id="_test_failure_coll__map">
<area shape="rect" id="node2" href="class_test.html" title="Base class for all test objects.All test objects should be a subclass of Test. Some test objects..." alt="" coords="5,101,56,131"/><area shape="rect" id="node4" href="class_exception.html" title="Exceptions thrown by failed assertions.Exception is an exception that serves descriptive strings thro..." alt="" coords="101,101,184,131"/><area shape="rect" id="node6" href="class_source_line.html" title="Represents a source line location.Used to capture the failure location in assertion." alt="" coords="36,5,129,35"/><area shape="rect" id="node8" href="class_message.html" title="Message associated to an Exception.A message is composed of two items:" alt="" coords="163,5,243,35"/></map>
<center><span class="legend">[<a href="graph_legend.html">legend</a>]</span></center></div>

<p><a href="class_test_failure-members.html">List of all members.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a0c1b4cee94278814ab7a4ba72f94dac3">TestFailure</a> (<a class="el" href="class_test.html">Test</a> *failedTest, <a class="el" href="class_exception.html">Exception</a> *thrownException, bool isError)</td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructs a <a class="el" href="class_test_failure.html" title="Record of a failed Test execution.A TestFailure collects a failed test together with the caught excep...">TestFailure</a> with the given test and exception.  <a href="#a0c1b4cee94278814ab7a4ba72f94dac3"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a117d2f3616bed325e97b0ac2fe7d9e4b">~TestFailure</a> ()</td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Deletes the owned exception.  <a href="#a117d2f3616bed325e97b0ac2fe7d9e4b"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="class_test.html">Test</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a8c7da6077f68897785a69cea6c2b7825">failedTest</a> () const </td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Gets the failed test.  <a href="#a8c7da6077f68897785a69cea6c2b7825"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="class_exception.html">Exception</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#ac12b8f4d9a6a1f130834cf08287d869d">thrownException</a> () const </td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Gets the thrown exception. Never <code>NULL</code>.  <a href="#ac12b8f4d9a6a1f130834cf08287d869d"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="class_source_line.html">SourceLine</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a0da7fc89d01c8b42c96cd0542eba58eb">sourceLine</a> () const </td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Gets the failure location.  <a href="#a0da7fc89d01c8b42c96cd0542eba58eb"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a0b6c1ee50d2186a4918f015d7879e8dd">isError</a> () const </td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Indicates if the failure is a failed assertion or an error.  <a href="#a0b6c1ee50d2186a4918f015d7879e8dd"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#af2f5978f08aa97106acdb09a57807a0e">failedTestName</a> () const </td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Gets the name of the failed test.  <a href="#af2f5978f08aa97106acdb09a57807a0e"></a><br/></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="class_test_failure.html">TestFailure</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#aeba45f44e148dc01146c615da438ab91">clone</a> () const </td></tr>
<tr><td colspan="2"><h2><a name="pro-attribs"></a>
Protected Attributes</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_test.html">Test</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a2ba79089909967b45aedc4992b51553a">m_failedTest</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_exception.html">Exception</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#a96bfae3c1f32d0c1729501d68016f431">m_thrownException</a></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#abf258e5bec289b51fb13147a62b8b75d">m_isError</a></td></tr>
<tr><td colspan="2"><h2><a name="pri-methods"></a>
Private Member Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#aeef404204f8114c31bb5d3049b22acab">TestFailure</a> (const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;other)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top"><a class="el" href="class_test_failure.html">TestFailure</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_test_failure.html#aa9eef2b8d4177f6b59e818810dc28b66">operator=</a> (const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;other)</td></tr>
</table>
<hr/><a name="details" id="details"></a><h2>Detailed Description</h2>
<div class="textblock"><p>Record of a failed <a class="el" href="class_test.html" title="Base class for all test objects.All test objects should be a subclass of Test. Some test objects...">Test</a> execution.</p>
<p>A <a class="el" href="class_test_failure.html" title="Record of a failed Test execution.A TestFailure collects a failed test together with the caught excep...">TestFailure</a> collects a failed test together with the caught exception. </p>
<p><a class="el" href="class_test_failure.html" title="Record of a failed Test execution.A TestFailure collects a failed test together with the caught excep...">TestFailure</a> assumes lifetime control for any exception passed to it. </p>
</div><hr/><h2>Constructor &amp; Destructor Documentation</h2>
<a class="anchor" id="a0c1b4cee94278814ab7a4ba72f94dac3"></a><!-- doxytag: member="TestFailure::TestFailure" ref="a0c1b4cee94278814ab7a4ba72f94dac3" args="(Test *failedTest, Exception *thrownException, bool isError)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">CPPUNIT_NS_BEGIN TestFailure::TestFailure </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_test.html">Test</a> *&#160;</td>
          <td class="paramname"><em>failedTest</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="class_exception.html">Exception</a> *&#160;</td>
          <td class="paramname"><em>thrownException</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>isError</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Constructs a <a class="el" href="class_test_failure.html" title="Record of a failed Test execution.A TestFailure collects a failed test together with the caught excep...">TestFailure</a> with the given test and exception. </p>

</div>
</div>
<a class="anchor" id="a117d2f3616bed325e97b0ac2fe7d9e4b"></a><!-- doxytag: member="TestFailure::~TestFailure" ref="a117d2f3616bed325e97b0ac2fe7d9e4b" args="()" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TestFailure::~TestFailure </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td><code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Deletes the owned exception. </p>

</div>
</div>
<a class="anchor" id="aeef404204f8114c31bb5d3049b22acab"></a><!-- doxytag: member="TestFailure::TestFailure" ref="aeef404204f8114c31bb5d3049b22acab" args="(const TestFailure &amp;other)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">TestFailure::TestFailure </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;&#160;</td>
          <td class="paramname"><em>other</em></td><td>)</td>
          <td><code> [private]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<hr/><h2>Member Function Documentation</h2>
<a class="anchor" id="aeba45f44e148dc01146c615da438ab91"></a><!-- doxytag: member="TestFailure::clone" ref="aeba45f44e148dc01146c615da438ab91" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test_failure.html">TestFailure</a> * TestFailure::clone </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a8c7da6077f68897785a69cea6c2b7825"></a><!-- doxytag: member="TestFailure::failedTest" ref="a8c7da6077f68897785a69cea6c2b7825" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test.html">Test</a> * TestFailure::failedTest </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the failed test. </p>

</div>
</div>
<a class="anchor" id="af2f5978f08aa97106acdb09a57807a0e"></a><!-- doxytag: member="TestFailure::failedTestName" ref="af2f5978f08aa97106acdb09a57807a0e" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::string TestFailure::failedTestName </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the name of the failed test. </p>

</div>
</div>
<a class="anchor" id="a0b6c1ee50d2186a4918f015d7879e8dd"></a><!-- doxytag: member="TestFailure::isError" ref="a0b6c1ee50d2186a4918f015d7879e8dd" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool TestFailure::isError </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Indicates if the failure is a failed assertion or an error. </p>

</div>
</div>
<a class="anchor" id="aa9eef2b8d4177f6b59e818810dc28b66"></a><!-- doxytag: member="TestFailure::operator=" ref="aa9eef2b8d4177f6b59e818810dc28b66" args="(const TestFailure &amp;other)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test_failure.html">TestFailure</a>&amp; TestFailure::operator= </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="class_test_failure.html">TestFailure</a> &amp;&#160;</td>
          <td class="paramname"><em>other</em></td><td>)</td>
          <td><code> [private]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a0da7fc89d01c8b42c96cd0542eba58eb"></a><!-- doxytag: member="TestFailure::sourceLine" ref="a0da7fc89d01c8b42c96cd0542eba58eb" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_source_line.html">SourceLine</a> TestFailure::sourceLine </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the failure location. </p>

</div>
</div>
<a class="anchor" id="ac12b8f4d9a6a1f130834cf08287d869d"></a><!-- doxytag: member="TestFailure::thrownException" ref="ac12b8f4d9a6a1f130834cf08287d869d" args="() const " -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_exception.html">Exception</a> * TestFailure::thrownException </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const<code> [virtual]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Gets the thrown exception. Never <code>NULL</code>. </p>

</div>
</div>
<hr/><h2>Member Data Documentation</h2>
<a class="anchor" id="a2ba79089909967b45aedc4992b51553a"></a><!-- doxytag: member="TestFailure::m_failedTest" ref="a2ba79089909967b45aedc4992b51553a" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_test.html">Test</a>* <a class="el" href="class_test_failure.html#a2ba79089909967b45aedc4992b51553a">TestFailure::m_failedTest</a><code> [protected]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="abf258e5bec289b51fb13147a62b8b75d"></a><!-- doxytag: member="TestFailure::m_isError" ref="abf258e5bec289b51fb13147a62b8b75d" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool <a class="el" href="class_test_failure.html#abf258e5bec289b51fb13147a62b8b75d">TestFailure::m_isError</a><code> [protected]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<a class="anchor" id="a96bfae3c1f32d0c1729501d68016f431"></a><!-- doxytag: member="TestFailure::m_thrownException" ref="a96bfae3c1f32d0c1729501d68016f431" args="" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_exception.html">Exception</a>* <a class="el" href="class_test_failure.html#a96bfae3c1f32d0c1729501d68016f431">TestFailure::m_thrownException</a><code> [protected]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li><a class="el" href="_test_failure_8h_source.html">TestFailure.h</a></li>
<li><a class="el" href="_test_failure_8cpp.html">TestFailure.cpp</a></li>
</ul>
</div>
<hr>
<table width="100%">
  <tr>
    <td width="10%" align="left" valign="center">
      <a href="http://sourceforge.net"> 
      <img
      src="http://sourceforge.net/sflogo.php?group_id=11795"
      width="88" height="31" border="0" alt="SourceForge Logo"></a>
    </td>
    <td width="20%" align="left" valign="center">
      hosts this site.
    </td>
    <td>
    </td>
    <td align="right" valign="center">
      Send comments to:<br>
      <a href="mailto:cppunit-devel@lists.sourceforge.net">CppUnit Developers</a>
    </td>
  </tr>
</table>

</body> 
</html>
